#!/bin/zsh

git submodule init && git submodule update

for folder in ${0:A:h}/*/files(:h)
do
    for file link in $(cat ${folder}/files)
    do
        if [[ -e ${~link} || -h ${~link} ]]
            # Apparently symlinks don't pass the -e test, dirs do
        then
            echo "$link exists, skipping"
        else
            [ ! -d ${~link:h} ] && mkdir -p ${~link:h}
            ln -s ${folder}/${file} ${~link}
        fi
    done
done

return 0

# vim: set ai et sw=4 syntax=zsh :
