#!/bin/bash

# Get zsh to handle the next bit.
[ ! -e /bin/zsh ] && sudo apt-get install zsh

zsh -c '
    # If this is over an ssh connection then do not be updating fonts etc
    CHANGE_X=$([ -z $SSH_CONNECTION ]; echo $?)

    git submodule init && git submodule update

    setopt extended_glob
    for folder in ${0:A:h}/*/files(:h)
    do
        for file link in $(cat ${folder}/files)
        do
            if [[ -e ${~link} || -h ${~link} ]]
                # Apparently symlinks do not pass the -e test, dirs do
            then
                echo "$link exists, skipping"
            else
                [ ! -d ${~link:h} ] && mkdir -p ${~link:h}
                ln -s ${folder}/${file} ${~link}
            fi
        done
        [ -e ${folder}/install ] && ${folder}/install
    done
'

# vim: set ai et sw=4 syntax=zsh :
