call pathogen#infect()
call pathogen#helptags()
syntax on
filetype plugin indent on

set modeline

set expandtab
set tabstop=4
set shiftwidth=4

" http://stackoverflow.com/questions/5601749/how-to-filter-out-files-by-extension-in-nerdtree
let NERDTreeIgnore = ['\.pyc$']
