#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

. "`dirname \`dirname \\\`readlink -f $0\\\`\``/script/lib.sh"
cd "${DOTFILES_FOLDER}"

declare -a SUCCESSFUL_INSTALLATIONS
declare -a SKIPPED_INSTALLATIONS
declare -a FAILED_INSTALLATIONS

main () {
    run_installers 3>"${STDOUT_LOGFILE}" 4>"${STDERR_LOGFILE}" 5>"${SKIP_LOGFILE}"

    report_successful_installations

    report_skipped_output
    report_skipped_installations

    report_stderr_output
    report_failed_installations

    suggest_issue_submission

    [ ${#FAILED_INSTALLATIONS} -eq 0 ]
}

run_installers () {
    local count=0
    local -a installers=($(find . -name install.sh))

    for installer in "${installers[@]}"
    do
        count=$(($count + 1))
        echo -n -e "\033[2K\r"
        echo -n -e "\r${count} / ${#installers[@]} -- Installing ${installer}\r"

        set +e
        sh -c "${installer}" 1>&3 2>&4 3>&5
        local installer_status=$?
        set -e

        case "${installer_status}" in
            0) SUCCESSFUL_INSTALLATIONS+=("${installer}") ;;
            1) SKIPPED_INSTALLATIONS+=("${installer}") ;;
            *) FAILED_INSTALLATIONS+=("${installer}") ;;
        esac
    done
}

report_successful_installations () {
    if [ ${#SUCCESSFUL_INSTALLATIONS} -eq 0 ]
    then
        return
    fi

    for install in "${SUCCESSFUL_INSTALLATIONS[@]}"
    do
        success "Installed ${install}"
    done
}

report_skipped_output () {
    if [ ! -s "${SKIP_LOGFILE}" ]
    then
        return
    fi

    echo ''

    skip 'Installation(s) were skipped for the following reasons:'
    echo ''
    cat "${SKIP_LOGFILE}"
}

report_skipped_installations () {
    if [ ${#SKIPPED_INSTALLATIONS} -eq 0 ]
    then
        return
    fi

    echo ''

    for install in "${SKIPPED_INSTALLATIONS[@]}"
    do
        skip "Skipped ${install}"
    done
}

report_stderr_output () {
    if [ ! -s "${STDERR_LOGFILE}" ]
    then
        return
    fi

    echo ''

    fail 'Standard error output:'
    echo ''
    cat "${STDERR_LOGFILE}"
}

report_failed_installations () {
    if [ ${#FAILED_INSTALLATIONS} -eq 0 ]
    then
        return
    fi

    echo ''

    for install in "${FAILED_INSTALLATIONS[@]}"
    do
        fail "Failed to install ${install}"
    done
}

suggest_issue_submission () {
    if [ ${#FAILED_INSTALLATIONS} -eq 0 ] && [ ! -s "${STDERR_LOGFILE}" ]
    then
        return
    fi

    echo ''
    info 'You can file an issue about this failure at https://github.com/matthewfranglen/dotfiles/issues'
    info "Please attach the log files in ${LOGS_FOLDER}"
}

main

