# This adds additional functionality to the zsh above and beyond the default settings

# $0 does not work if this is symlinked. Essentially the script is not invoked or sourced
# see http://stackoverflow.com/questions/9901210/bash-source0-equivalent-in-zsh
ZSHRC=${ZDOTDIR-~}/.zshrc
ZSH_FOLDER=${ZSHRC:A:h}

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory notify
bindkey -v
# End of lines configured by zsh-newuser-install

# The following lines were added by compinstall
zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _list _expand _complete _ignored _match
zstyle ':completion:*' completions 1
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' glob 1
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent pwd .. directory
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=** r:|=**'
zstyle ':completion:*' max-errors 0
zstyle ':completion:*' menu select=2
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' substitute 1
zstyle ':completion:*' use-compctl true
zstyle ':completion:*' verbose true
zstyle :compinstall filename "$HOME/.zshrc"

fpath=(${ZSH_FOLDER}/autocomplete $fpath)

autoload -Uz compinit
compinit
# End of lines added by compinstall

# This allows exclusions and the like in the pattern expansion
setopt extended_glob

###############################
# make less more friendly for #
# non-text input files, see   #
# lesspipe(1)                 #
###############################
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"


####################
# MODULES AND PATH #
####################

# load antigen.
. ${ZSH_FOLDER}/antigen/antigen.zsh
antigen-bundle zsh-users/zsh-syntax-highlighting
antigen-bundle Tarrasch/zsh-functional
antigen-apply

# Load the fasd completion system.
# See https://github.com/clvv/fasd
PATH=$PATH:${ZSH_FOLDER}/packages/fasd
eval "$(${ZSH_FOLDER}/packages/fasd/fasd --init auto)"

# add bin folder to path
PATH=$PATH:${ZSH_FOLDER}/bin:${ZSH_FOLDER}/host-specific-bin


######################
# PROMPT AND ALIASES #
######################

. ${ZSH_FOLDER}/config/aliases
. ${ZSH_FOLDER}/config/prompt


###############
# KEY MAPPING #
###############

# Disable ctrl-s ctrl-q (suspend, resume. frequently really really annoying!)
# http://geekanova.blogspot.co.uk/2012/11/ctrl-s-freezes-terminal.html
stty -ixon -ixoff

# keyboard mappings.
# Don't want to run this on remote hosts!
# This updates X! Doing this via a keyboard map option now, 
# hopefully this approach will stop it occasionally failing.
[ -z "$SSH_CONNECTION" ] && setxkbmap -option caps:escape

# This allows control-r to be used to perform a reverse search
bindkey -M viins '^r' history-incremental-search-backward
bindkey -M vicmd '^r' history-incremental-search-backward

# Extra key mappings
bindkey "^[." insert-last-word

# alt-hjkl for movement in insert (ctrl-h is backspace!)
bindkey -M viins '^[h' vi-backward-blank-word
bindkey -M viins '^[k' up-line-or-history
bindkey -M viins '^[j' down-line-or-history
bindkey -M viins '^[l' vi-forward-blank-word


################
# EDITOR STUFF #
################

export VISUAL=/usr/bin/vim
export EDITOR=/usr/bin/vim
export SVN_EDITOR=/usr/bin/vim
export GIT_EDITOR=/usr/bin/vim
export LESS=ir
export JAVA_HOME=/usr/lib/jvm/default-java

# vim: set ai et sw=4 syntax=zsh :
